Add function for delete categories
DmytroRoik/cursor-react-app pull request #19
Opened 2020-04-17 16:59 UTC by karinayurchenko

2020-04-17 18:50 UTC, arbuzaicer commented on src/components/BtnDeleteModal/BtnDeleteModal.js
> +export default function AlertDialog(props) {
export const AlertDialog = (props) => { //плюс, зробіть деструктуризацію пропсів відразу { variables }

}

2020-04-17 18:51 UTC, arbuzaicer commented on src/components/BtnDeleteModal/BtnDeleteModal.js
> +  return (
Якщо ваша функція тільки презентаційна (без внутрішньої логіки) робіть так
export const YourFunc = ({props, data, etc}) => (
все що в return
)

2020-04-17 18:52 UTC, arbuzaicer commented on src/components/BtnDeleteModal/BtnDeleteModal.js
> +        open={props.open}
open={open} //диструктуруйте змінні в пропсах

2020-04-17 18:54 UTC, arbuzaicer commented on src/components/Dropdown/Dropdown.js
> +export default function Dropdown(props) {
export default ({your, props, data}) => {
...
}

2020-04-17 18:57 UTC, arbuzaicer commented on src/components/TableCategories/TableCategories.js
> +  const [open, OpenModal] = useState(false);
називайте булеві змінні загально прийнято: вони повинні починатись з префікса is
Ex: isOpen, setIsOpenModal

2020-04-17 18:58 UTC, arbuzaicer commented on src/components/TableCategories/TableCategories.js
> +  }, []);
пустий масив можна видалити

2020-04-17 19:02 UTC, arbuzaicer requested changes
Reviewed.

2020-04-17 22:26 UTC, karinayurchenko commented on src/components/BtnDeleteModal/BtnDeleteModal.js
> +  return (
все пофіксила

2020-04-17 23:38 UTC, DmytroRoik approved these changes

2020-04-18 16:58 UTC, arbuzaicer approved these changes

2020-04-18 18:15 UTC, Malfit approved these changes

2020-04-18 18:16 UTC, merged