Feature/load icons from server
DmytroRoik/cursor-react-app pull request #25
Opened 2020-04-21 16:11 UTC by IrynaTrush

2020-04-21 18:15 UTC, DmytroRoik commented on src/redux/actions/iconSelector.actions.js
> +
' LOAD_ICONS_SUCCESS'  має бути без пробілів

2020-04-21 19:15 UTC, IrynaTrush commented on src/redux/actions/iconSelector.actions.js
> +
виправила

2020-04-21 20:13 UTC, varvadyk approved these changes

2020-04-22 13:46 UTC, arbuzaicer commented on src/pages/New-сategories/select.js
>  const useStyles = makeStyles((theme) => ({
в цьому місці eslint тобі 100% червоним малює.
(theme) => ({  заміни на:    theme => ({

2020-04-22 13:51 UTC, arbuzaicer requested changes
Чудово. Але в плані структуризації я б дещо підправив.

2020-04-22 13:51 UTC, arbuzaicer commented on src/redux/store.js
> +  rootReducer, homeReducer, chartsReducer, categoriesReducer, iconSelectorReducer
можливо не варто для такої штуки як icons створювати власний instance для редьюесера, селектора і екшна. Ми коли створювали базові конструкції редаксу - було створени rootReducer - фактично така штука, яка буде використовуватись для багатьох сторінок. Це можливо тільки моя думка, але я б всі твої маніпуляції з іконками робив би в директорії root: типу заюзав би rootReducer, rootActions, rootSelectors

2020-04-22 14:36 UTC, Nazar-Sch approved these changes

2020-04-22 17:19 UTC, DmytroRoik commented on src/redux/store.js
> +  rootReducer, homeReducer, chartsReducer, categoriesReducer, iconSelectorReducer
@IrynaTrush перенеси логіку свого редусера в  rootReducer

2020-04-22 19:31 UTC, Malfit approved these changes

2020-04-22 19:31 UTC, Malfit commented on src/pages/New-сategories/select.js
>            </MenuItem>
поправьте отступы

2020-04-22 19:54 UTC, IrynaTrush commented on src/redux/store.js
> +  rootReducer, homeReducer, chartsReducer, categoriesReducer, iconSelectorReducer
дякую, виправила

2020-04-22 19:54 UTC, IrynaTrush commented on src/pages/New-сategories/select.js
>            </MenuItem>
виправила

2020-04-23 09:05 UTC, DmytroRoik approved these changes

2020-04-23 09:58 UTC, arbuzaicer approved these changes

2020-04-23 10:11 UTC, merged