User data/load data user data balance
DmytroRoik/cursor-react-app pull request #28
Opened 2020-04-23 19:34 UTC by Nazar-Sch

2020-04-23 20:13 UTC, arbuzaicer commented on src/redux/actions/profile.actions.js
> +import api from '../../api/api';
я думаю що створювати свій власний редюсер для 2 даних - не варто. В rootReducer - вже є поле balance в initialState тому тобі просто потрібно його трохи змінити (загалом це стосується і actions і reducers і selectors) - пиши все в root

2020-04-23 20:14 UTC, arbuzaicer requested changes
круто. але я би переніс всю логіку в rootReducer/action/selector

2020-04-23 20:41 UTC, IrynaTrush approved these changes

2020-04-24 11:40 UTC, Malfit approved these changes

2020-04-24 18:20 UTC, Malfit approved these changes

2020-04-24 19:26 UTC, Nazar-Sch commented on src/redux/actions/profile.actions.js
> +import api from '../../api/api';
зафіксив)

2020-04-24 20:20 UTC, Malfit approved these changes

2020-04-25 19:10 UTC, DmytroRoik approved these changes

2020-04-25 19:11 UTC, arbuzaicer approved these changes

2020-04-25 19:36 UTC, VasylykSerhiy approved these changes

2020-04-25 20:47 UTC, IrynaTrush approved these changes

2020-04-25 23:04 UTC, merged