add reusable balance component
DmytroRoik/cursor-react-app pull request #7
Opened 2020-04-05 17:47 UTC by varvadyk

2020-04-05 21:35 UTC, DmytroRoik approved these changes

2020-04-06 10:02 UTC, VasylykSerhiy approved these changes

2020-04-06 17:13 UTC, arbuzaicer commented on src/components/Balance/Balance.js
> +const Balance = ({ suma }) => (
Мені не дуже подобається назва пропсів - suma - це український варіант, описаний англійською. Можливо - total? summary?

2020-04-06 17:37 UTC, arbuzaicer commented on src/layout/style.scss
> +   justify-content: right;
Я як то не дуже зрозумів, що зачить ця строчка: 
https://css-tricks.com/almanac/properties/j/justify-content/

2020-04-06 17:39 UTC, arbuzaicer requested changes
Виправив деякі моменти.

2020-04-06 18:34 UTC, varvadyk commented on src/layout/style.scss
> +   justify-content: right;
виправила

2020-04-06 18:34 UTC, varvadyk commented on src/components/Balance/Balance.js
> +const Balance = ({ suma }) => (
Дякую,старатимусь називати більш логічно

2020-04-06 18:39 UTC, arbuzaicer approved these changes

2020-04-06 18:46 UTC, merged